runtime: python310  # Use the Python runtime version for your app

entrypoint: streamlit run your_app.py --server.port=8080

env_variables:
  STREAMLIT_SERVER_PORT: 8080  # Make sure the port matches the one specified by GAE

instance_class: F2  # You can choose an instance class based on your app's needs

