[numOfChannels]
channelIDRequests = []
num1 = 0

[numofWebsites]
WebsiteRequests = []
num2 = 0

[numofPIrequests]
PIRequests = []
num3 = 0


[secretKey]
youtubeAPIKEY = 'AIzaSyAZOmgb9FhMLlAGF5yxkbG8B4p1lSYN4eI'
youtubeChannelID = 'UC9AliDm1dH2RUxyogVe1j9A'
